package org.application.repositories.custom;

import org.springframework.stereotype.Repository;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

@Repository
public class RequestRecordRepo {

    private String jdbcUrl = "jdbc:h2:mem:db";
    private String username = "sa";
    private String password = "";

    private String createRecordTable =
            "CREATE TABLE records (" +
                    "id bigint generated by default as identity," +
                    "type varchar(255)," +
                    "out varchar(255)," +
                    "to varchar(255)," +
                    "date date," +
                    "primary key (id)" +
                    ");";

    private String deleteRecordTable = "DROP TABLE records;";

    private Connection connection;

    @PostConstruct
    public void init() throws SQLException {
        connection = DriverManager.getConnection(jdbcUrl, username, password);
        Statement statement = connection.createStatement();

        statement.execute(createRecordTable);
    }

    @PreDestroy
    public void destroy() throws SQLException {
        Statement statement = connection.createStatement();

        statement.execute(deleteRecordTable);
    }

}
